local function createLanguagesGroup(palette, zitch)
  return {
    -- CSS
    cssTagName = zitch.Purple,
    cssSelectorOp = zitch.Purple,
    cssSelectorOp2 = zitch.Purple,
    cssClassName = zitch.Blue,
    cssClassNameDot = zitch.Blue,
    cssIdentifier = zitch.Green,
    cssUnitDecorators = zitch.Purple,
    cssColor = zitch.Purple,
    cssImportant = zitch.Purple,
    cssFunction = zitch.Orange,
    cssProp = zitch.Pink,
    cssAttr = zitch.Foreground,
    cssPseudoClassId = zitch.Pink,
    cssNoise = zitch.Pink,
    cssCustomProp = zitch.Foreground,
    cssMediaType = zitch.Purple,

    -- HTML
    htmlTag = zitch.Foreground,
    htmlEndTag = zitch.Foreground,
    htmlTagName = zitch.Purple,
    htmlArg = zitch.Pink,
    htmlScriptTag = zitch.Purple,
    htmlTagN = zitch.Purple,
    htmlSpecialTagName = zitch.Purple,
    htmlTitle = zitch.Foreground,
    htmlH1 = zitch.Foreground,
    htmlSpecialChar = zitch.Green,
    htmlLink = zitch.ForegroundUnderline,
    htmlBold = zitch.ForegroundBold,
    htmlBoldUnderline = { fg = palette.white, gui = "bold,underline" },
    htmlBoldItalic = { fg = palette.white, gui = "bold,italic" },
    htmlBoldUnderlineItalic = { fg = palette.white, gui = "bold,italic" },
    htmlItalic = { fg = palette.white, gui = "italic" },

    -- JAVASCRIPT
    javaScriptMember = zitch.Foreground,
    javaScriptOperator = zitch.Purple,
    javaScriptType = zitch.Blue,
    javaScriptParens = zitch.Orange,
    javaScriptBraces = zitch.Orange,
    javaScriptIdentifier = zitch.Purple,
    javaScriptNull = zitch.Purple,
    javaScriptReserved = zitch.Purple,
    javaScriptRepeat = zitch.Purple,
    javaScriptConditional = zitch.Purple,
    javaScriptException = zitch.Purple,
    javaScriptStatement = zitch.Purple,
    javaScriptStringD = zitch.Green,
    javaScriptStringT = zitch.Green,
    javaScriptGlobal = zitch.Foreground,
    javaScriptLabel = zitch.Purple,
    javaScriptBranch = zitch.Purple,
    javaScriptFunction = zitch.Orange,
    javaScriptBoolean = zitch.Purple,

    -- JAVASCRIPTREACT
    jsxTagName = zitch.Purple,
    jsxComponentName = zitch.Orange,
    jsxCloseString = zitch.Foreground,
    jsxAttrib = zitch.Pink,
    jsxEqual = zitch.Purple,

    -- JSON
    jsonKeyword = zitch.Purple,
    jsonQuote = zitch.Green,
    jsonBraces = zitch.Pink,
    jsonString = zitch.Green,
    jsonNoise = zitch.Pink,
    jsonBoolean = zitch.Green,
    jsonNull = zitch.Green,

    -- MARKDOWN
    markdownItalic = { fg = palette.white, gui = "italic" },
    markdownBold = zitch.ForegroundBold,
    markdownBoldItalic = { fg = palette.white, gui = "bold,italic" },
    markdownH1 = zitch.Orange,
    markdownH2 = zitch.Orange,
    markdownH3 = zitch.Orange,
    markdownH4 = zitch.Orange,
    markdownH5 = zitch.Orange,
    markdownH6 = zitch.Orange,
    markdownBlockquote = zitch.Gray,
    markdownListMarker = zitch.Purple,
    markdownOrderedListMarker = zitch.Gray,
    markdownRule = zitch.Gray,
    markdownHeadingRule = zitch.Gray,
    markdownUrlDelimiter = zitch.Foreground,
    markdownLinkDelimiter = zitch.Foreground,
    markdownLinkTextDelimiter = zitch.Foreground,
    markdownHeadingDelimiter = zitch.Purple,
    markdownUrl = zitch.PurpleUnderline,
    markdownUrlTitleDelimiter = zitch.Foreground,
    markdownLinkText = zitch.Green,
    markdownIdDeclaration = zitch.GreenUnderline,
    markdownCode = zitch.Green,

    -- SASS
    sassVariable = zitch.Foreground,

    -- TYPESCRIPT
    typescriptDestructureVariable = zitch.Foreground,
    typescriptAssign = zitch.Purple,
    typescriptReserved = zitch.Purple,
    typescriptLabel = zitch.Pink,
    typescriptDestructureLabel = zitch.Foreground,
    typescriptObjectDestructure = zitch.Foreground,
    typescriptTupleLable = zitch.Foreground,
    typescriptFuncKeyword = zitch.Purple,
    typescriptIdentifier = zitch.Orange,
    typescriptBraces = zitch.Orange,
    typescriptEndColons = zitch.Foreground,
    typescriptLogicSymbols = zitch.Orange,
    typescriptDocSeeTag = zitch.Gray,
    typescriptDocParam = zitch.Gray,
    typescriptDocTags = zitch.Gray,
    typescriptParens = zitch.Orange,
    typescriptOpSymbols = zitch.Orange,
    typescriptNull = zitch.Purple,
    typescriptInterpolationDelimiter = zitch.Purple,
    typescriptArrowFunc = zitch.Purple,
    typescriptCharacter = zitch.Orange,
    typescriptUnion = zitch.Orange,
    typescriptDotNotation = zitch.Orange,
    typescriptGlobalObjectDot = zitch.Orange,
    typescriptStatementKeyword = zitch.Purple,
    typescriptInterfaceName = zitch.Blue,
    typescriptMember = zitch.Pink,
    typescriptType = zitch.Purple,
    typescriptPredefinedType = zitch.Purple,
    typescriptFuncType = zitch.Blue,
    typescriptFuncTypeArrow = zitch.Blue,
    typescriptFuncName = zitch.Orange,
    typescriptCastKeyword = zitch.Purple,
    typescriptGlobal = zitch.Blue,
    typescriptTypeReference = zitch.Blue,
    typescriptAliasDeclaration = zitch.Blue,
    typescriptVariable = zitch.Purple,
    typescriptCall = zitch.Foreground,
    typescriptModule = zitch.Purple,
    typescriptEnum = zitch.Blue,
    typescriptForOperator = zitch.Purple,
    typescriptBranch = zitch.Purple,
    typescriptAmbientDeclaration = zitch.Purple,
    typescriptTypeBracket = zitch.Pink,
    typescriptFuncComma = zitch.Pink,
    typescriptDefaultParam = zitch.Purple,
    typescriptGlobalMethod = zitch.Orange,
    typescriptNumberStaticProp = zitch.Foreground,
    typescriptNumberStaticMethod = zitch.Orange,
    typescriptNumberMethod = zitch.Orange,
    typescriptStringMethod = zitch.Orange,
    typescriptArrayMethod = zitch.Orange,
    typescriptObjectStaticMethod = zitch.Orange,
    typescriptObjectMethod = zitch.Orange,
    typescriptSymbolStaticProp = zitch.Orange,
    typescriptSymbolStaticMethod = zitch.Orange,
    typescriptFunctionMethod = zitch.Orange,
    typescriptMathStaticMethod = zitch.Orange,
    typescriptDateMethod = zitch.Orange,
    typescriptDateStaticMethod = zitch.Orange,
    typescriptJSONStaticMethod = zitch.Orange,
    typescriptRegExpMethod = zitch.Orange,
    typescriptES6MapMethod = zitch.Orange,
    typescriptES6MapProp = zitch.Pink,
    typescriptES6SetProp = zitch.Pink,
    typescriptES6SetMethod = zitch.Orange,
    typescriptProxyAPI = zitch.Orange,
    typescriptPromiseStaticMethod = zitch.Orange,
    typescriptPromiseMethod = zitch.Orange,
    typescriptReflectMethod = zitch.Orange,
    typescriptIntlMethod = zitch.Orange,
    typescriptTestGlobal = zitch.Orange,
    typescriptNodeGlobal = zitch.Foreground,
    typescriptBOM = zitch.Blue,
    typescriptBOMWindowProp = zitch.Foreground,
    typescriptBOMWindowMethod = zitch.Orange,
    typescriptBOMWindowEvent = zitch.Orange,
    typescriptBOMNavigatorMethod = zitch.Orange,
    typescriptServiceWorkerMethod = zitch.Orange,
    typescriptBOMLocationMethod = zitch.Orange,
    typescriptBOMNavigatorProp = zitch.Foreground,
    typescriptBOMLocationProp = zitch.Foreground,
    typescriptBOMHistoryProp = zitch.Foreground,
    typescriptBOMHistoryMethod = zitch.Orange,
    typescriptConsoleMethod = zitch.Orange,
    typescriptXHRProp = zitch.Pink,
    typescriptXHRMethod = zitch.Orange,
    typescriptFileMethod = zitch.Orange,
    typescriptFileReaderProp = zitch.Pink,
    typescriptFileReaderMethod = zitch.Orange,
    typescriptFileListMethod = zitch.Orange,
    typescriptBlobMethod = zitch.Orange,
    typescriptURLUtilsProp = zitch.Pink,
    typescriptURLStaticMethod = zitch.Orange,
    typescriptSubtleCryptoMethod = zitch.Orange,
    typescriptCryptoProp = zitch.Pink,
    typescriptCryptoMethod = zitch.Orange,
    typescriptHeadersMethod = zitch.Orange,
    typescriptRequestProp = zitch.Pink,
    typescriptRequestMethod = zitch.Orange,
    typescriptResponseProp = zitch.Pink,
    typescriptResponseMethod = zitch.Orange,
    typescriptServiceWorkerProp = zitch.Pink,
    typescriptCacheMethod = zitch.Orange,
    typescriptEncodingProp = zitch.Pink,
    typescriptEncodingMethod = zitch.Orange,
    typescriptGeolocationMethod = zitch.Orange,
    typescriptBOMNetworkProp = zitch.Pink,
    typescriptPaymentMethod = zitch.Orange,
    typescriptPaymentProp = zitch.Pink,
    typescriptPaymentEvent = zitch.Orange,
    typescriptPaymentResponseMethod = zitch.Orange,
    typescriptPaymentResponseProp = zitch.Pink,
    typescriptPaymentAddressProp = zitch.Pink,
    typescriptPaymentShippingOptionProp = zitch.Pink,
    typescriptDOMNodeProp = zitch.Pink,
    typescriptDOMNodeMethod = zitch.Orange,
    typescriptDOMNodeType = zitch.Purple,
    typescriptDOMElemAttrs = zitch.Pink,
    typescriptDOMElemFuncs = zitch.Orange,
    typescriptDOMDocProp = zitch.Pink,
    typescriptDOMDocMethod = zitch.Orange,
    typescriptDOMEventTargetMethod = zitch.Orange,
    typescriptDOMEventCons = zitch.Blue,
    typescriptDOMEventProp = zitch.Pink,
    typescriptDOMEventMethod = zitch.Orange,
    typescriptDOMStorage = zitch.Pink,
    typescriptDOMStorageProp = zitch.Pink,
    typescriptDOMStorageMethod = zitch.Orange,
    typescriptDOMFormProp = zitch.Pink,
    typescriptDOMFormMethod = zitch.Orange,
    typescriptDOMStyle = zitch.Pink,
    typescriptUnaryOp = zitch.Purple,
    typescriptTernary = zitch.Purple,
    typescriptBinaryOp = zitch.Purple,
    typescriptMethodAccessor = zitch.Purple,

    -- TYPESCRIPTREACT
    tsxRegion = zitch.Foreground,
    tsxAttrib = zitch.Pink,

    -- YAML
    yamlBlockMappingKey = zitch.Purple,
    yamlConstant = zitch.Pink,
    yamlBlockCollectionItemStart = zitch.Foreground,
    yamlFlowIndicator = zitch.Orange,
    yamlKeyValueDelimiter = zitch.Pink,
  }
end

return {
  create = createLanguagesGroup,
}
