local M = {}

---@param palette ZitchdogPalette
---@param zitch_pattern ZitchdogHighlights
---@param config ZitchdogConfig
---@return ZitchdogHighlights
function M.create(palette, zitch_pattern, config)
	local groups = {
		-- Highlight Groups setting all Available Colors as Foregrounds
		ZitchPurple = { fg = palette.purple },
		ZitchGreen = { fg = palette.green },
		ZitchOrange = { fg = palette.orange },
		ZitchCoral = { fg = palette.coral },
		ZitchCyan = { fg = palette.cyan },
		ZitchRed = { fg = palette.red },
		ZitchPink = { fg = palette.pink },
		ZitchWhite = { fg = palette.white },
		ZitchGray = { fg = palette.gray },
		ZitchAsh = { fg = palette.ash },
		ZitchBlack = { fg = palette.black },
		ZitchDarkBlack = { fg = palette.darkblack },
		ZitchMagenta = { fg = palette.magenta },
		ZitchYellow = { fg = palette.yellow },
		ZitchMauve = { fg = palette.mauve },
		ZitchBlue = { fg = palette.blue },
		ZitchCharcoal = { fg = palette.charcoal },
		ZitchSlate = { fg = palette.slate },
		ZitchGraphite = { fg = palette.graphite },
		ZitchLilac = { fg = palette.lilac },
		ZitchAmethyst = { fg = palette.amethyst },
		ZitchAubergine = { fg = palette.aubergine },
		ZitchEbony = { fg = palette.ebony },
		ZitchMaroon = { fg = palette.maroon },
		ZitchPine = { fg = palette.pine },
		ZitchIndigo = { fg = palette.indigo },
		ZitchUmber = { fg = palette.umber },
		ZitchClay = { fg = palette.clay },
		ZitchMulberry = { fg = palette.mulberry },
		ZitchTeal = { fg = palette.teal },
		ZitchLightBlack = { fg = palette.lightblack },
		ZitchBgPurple = { bg = palette.purple },
		ZitchBgGreen = { bg = palette.green },
		ZitchBgOrange = { bg = palette.orange },
		ZitchBgCoral = { bg = palette.coral },
		ZitchBgCyan = { bg = palette.cyan },
		ZitchBgRed = { bg = palette.red },
		ZitchBgPink = { bg = palette.pink },
		ZitchBgWhite = { bg = palette.white },
		ZitchBgGray = { bg = palette.gray },
		ZitchBgAsh = { bg = palette.ash },
		ZitchBgBlack = { bg = palette.black },
		ZitchBgDarkBlack = { bg = palette.darkblack },
		ZitchBgMagenta = { bg = palette.magenta },
		ZitchBgYellow = { bg = palette.yellow },
		ZitchBgMauve = { bg = palette.mauve },
		ZitchBgBlue = { bg = palette.blue },
		ZitchBgCharcoal = { bg = palette.charcoal },
		ZitchBgSlate = { bg = palette.slate },
		ZitchBgGraphite = { bg = palette.graphite },
		ZitchBgLilac = { bg = palette.lilac },
		ZitchBgAmethyst = { bg = palette.amethyst },
		ZitchBgAubergine = { bg = palette.aubergine },
		ZitchBgEbony = { bg = palette.ebony },
		ZitchBgMaroon = { bg = palette.maroon },
		ZitchBgPine = { bg = palette.pine },
		ZitchBgIndigo = { bg = palette.indigo },
		ZitchBgUmber = { bg = palette.umber },
		ZitchBgClay = { bg = palette.clay },
		ZitchBgMulberry = { bg = palette.mulberry },
		ZitchBgTeal = { bg = palette.teal },
		ZitchBgLightBlack = { bg = palette.lightblack },
	}
	return groups
end

return M
