return {
  purple = nil,
  green = nil,
  orange = nil,
  red = nil,
  pink = nil,
  white = nil,
  gray = nil,
  black = nil,
  purple_faded = nil,
  blue = nil,
  darkgray = nil,
  lightgray = nil,
  inactivegray = nil,
  lightergray = nil,
  purple1 = nil,
  purple2 = nil,
  purple3 = nil,
}
